export { default as activeFile } from './activeFile.svg'
export { ReactComponent as ellipse1 } from './ellipse1.svg'
export { ReactComponent as ellipse2 } from './ellipse2.svg'
export { default as savedFile } from './savedFile.svg'
export { ReactComponent as savedIcon } from './savedIcon.svg'
export { ReactComponent as vector1 } from './vector1.svg'
