export { default as activeFile } from './activeFile.svg'
export { default as ellipse1 } from './ellipse1.svg'
export { default as ellipse2 } from './ellipse2.svg'
export { default as savedFile } from './savedFile.svg'
export { default as savedIcon } from './savedIcon.svg'
export { default as deletebutton } from './deletebutton.svg'
