export { ReactComponent as editingFile } from './editingFile.svg'
export { ReactComponent as ellipse1 } from './ellipse1.svg'
export { ReactComponent as ellipse2 } from './ellipse2.svg'
export { default as fileText1 } from './fileText1.svg'
export { default as FileActive } from './file-active.svg'
export { ReactComponent as savedIcon } from './savedIcon.svg'
export { ReactComponent as vector1 } from './vector1.svg'
